[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "classtab"
version = "0.1.0"

dependencies = [
	"Django == 4.1.*"
]

[project.optional-dependencies]
types = [
	"django-stubs == 1.13.*",
]
